# Generated by Django 2.2.3 on 2020-02-09 19:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_for_delivery', models.BooleanField(default=False)),
                ('order', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_package_delivered', models.BooleanField(default=False)),
                ('reference_code', models.CharField(blank=True, max_length=20, null=True)),
                ('package_being_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
